[project]
name = "wikipedia-bot"
version = "0.5.1"
requires-python = "==3.11.2"
dependencies = [
    "loguru>=0.7.3",
    "pywikibot>=10.2.0",
    "sentry-sdk>=2.32.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
