[project]
name = "wikipedia-bot"
version = "0.5.2"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "pywikibot>=10.2.0",
    "sentry-sdk>=2.32.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "ruff>=0.12.2",
]

[tool.ruff.lint]
select = [
    "A", "ANN", "ARG", "B", "BLE", "EM", "ERA", "FBT", "FIX", "FLY", "FURB", "I", "ICN",
    "INP", "ISC", "N", "PERF", "PIE", "PLC", "PLE", "PT", "Q", "RET", "RSE", "RUF",
    "SIM", "SLF", "T20", "TID", "TRY", "W",
#    "C4", "COM", "D", "E", "PLR", "PLW", "PTH", "S", "UP",
]

[tool.bumpversion]
current_version = "0.5.2"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "tasks/__init__.py"
